# Generated by Django 3.2.4 on 2021-06-28 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('perceived_url', models.TextField(blank=True, null=True)),
                ('referrer_url', models.TextField(blank=True, null=True)),
                ('item_json', models.TextField(blank=True, null=True)),
                ('patron_json', models.TextField(blank=True, null=True)),
                ('ezb_db_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'request entry',
                'verbose_name_plural': 'request entries',
                'ordering': ['-created'],
            },
        ),
    ]
